load("//tensorflow/lite/micro:build_def.bzl", "generate_cc_arrays")

package(
    default_visibility = ["//visibility:public"],
)

exports_files(
    srcs = [
        "fall_detection_model.tflite",
    ],
    visibility = ["//tensorflow/lite/micro/examples/imu_fall_detection:__subpackages__"],
)
